"""controle_estoque

Revision ID: e3f0fd0b1858
Revises: fc6c499ff808
Create Date: 2026-06-24 15:05:45.134455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f0fd0b1858'
down_revision: Union[str, Sequence[str], None] = 'fc6c499ff808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientes', sa.Column('quantidade_estoque', sa.Float(), nullable=False))
    op.add_column('ingredientes', sa.Column('estoque_minimo', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredientes', 'estoque_minimo')
    op.drop_column('ingredientes', 'quantidade_estoque')
    # ### end Alembic commands ###
