/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

declare const self: ServiceWorkerGlobalScope

// Precache all static assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// ── API caching (NetworkFirst with 5s timeout) ──────────────────

registerRoute(
  /^https?:\/\/.*\/api\/v1\/.*$/i,
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
)

// ── Google Fonts CSS (StaleWhileRevalidate) ──────────────────────

registerRoute(
  /^https?:\/\/fonts\.googleapis\.com\/.*$/i,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-css',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
)

// ── Google Fonts webfonts (CacheFirst, 1 year) ───────────────────

registerRoute(
  /^https?:\/\/fonts\.gstatic\.com\/.*$/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
)

// ── Background Sync handler ──────────────────────────────────────

self.addEventListener('sync', (event) => {
  const syncEvent = event as unknown as { tag: string; waitUntil(p: Promise<unknown>): void }
  if (syncEvent.tag === 'sync-mutations') {
    syncEvent.waitUntil(notifyClientsToSync())
  }
})

async function notifyClientsToSync() {
  const clients = await self.clients.matchAll({ type: 'window' })
  for (const client of clients) {
    client.postMessage({ type: 'PROCESS_MUTATIONS' })
  }
}

self.addEventListener('install', () => {
  self.skipWaiting()
})
