/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

declare const self: ServiceWorkerGlobalScope

// Precache all static assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// ── API caching (NetworkFirst with 5s timeout) ──────────────────

registerRoute(
  /^https?:\/\/.*\/api\/v1\/.*$/i,
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
)

// ── Google Fonts CSS (StaleWhileRevalidate) ──────────────────────

registerRoute(
  /^https?:\/\/fonts\.googleapis\.com\/.*$/i,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-css',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
)

// ── Google Fonts webfonts (CacheFirst, 1 year) ───────────────────

registerRoute(
  /^https?:\/\/fonts\.gstatic\.com\/.*$/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
)

// ── Background Sync handler ──────────────────────────────────────

// Interface portável para SyncEvent — não depende da disponibilidade
// do tipo global SyncEvent (Background Sync API experimental)
interface SyncEventLike extends ExtendableEvent {
  tag: string
  waitUntil(p: Promise<unknown>): void
}

self.addEventListener('sync', (event) => {
  const syncEvent = event as SyncEventLike
  if (syncEvent.tag === 'sync-mutations') {
    syncEvent.waitUntil(notifyClientsToSync())
  }
})

async function notifyClientsToSync() {
  const clients = await self.clients.matchAll({ type: 'window' })
  for (const client of clients) {
    client.postMessage({ type: 'PROCESS_MUTATIONS' })
  }
}

// ── Message handler: clear auth cache on logout (TM-005) ────────

self.addEventListener('message', (event) => {
  if (event.data?.type === 'CLEAR_AUTH_CACHE') {
    event.waitUntil(clearAuthCache())
  }
})

/** Retorna true se a URL parece ser de uma rota admin (não pública) */
function _isAdminRoute(url: string): boolean {
  // Rotas públicas conhecidas — mantém cache
  if (url.includes('/api/v1/publico/')) return false
  if (url.includes('/api/v1/admin/login')) return false
  // Qualquer outra rota /api/v1/ pode conter dados admin
  return url.includes('/api/v1/')
}

async function clearAuthCache() {
  const cacheNames = ['api-cache']
  const opening = cacheNames.map(name => caches.open(name))
  const cachesToClear = await Promise.all(opening)

  await Promise.all(
    cachesToClear.map(cache =>
      cache.keys().then(requests =>
        Promise.all(
          requests
            .filter(r => _isAdminRoute(r.url))
            .map(r => cache.delete(r))
        )
      )
    )
  )

  // Notifica as janelas que o cache foi limpo
  const clients = await self.clients.matchAll({ type: 'window' })
  for (const client of clients) {
    client.postMessage({ type: 'AUTH_CACHE_CLEARED' })
  }
}

self.addEventListener('install', () => {
  self.skipWaiting()
})
